### ISSUE TITLE
Followed Instructions with Composer

### ISSUE THREAD

**Issue by kreativmind** [goalgorilla/drupal_social#238]
Then install via UI
An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /core/install.php?rewrite=ok&profile=social&langcode=en&id=2&op=do_nojs&op=do
StatusText: Internal Server Error
ResponseText: 

Error log reports:
[12-Jul-2016 12:08:31 America/Chicago] PHP Fatal error:  Interface 'CommerceGuys\Zone\Model\ZoneInterface' not found in /public_html/mydomain/profiles/social/modules/contrib/address/src/Entity/ZoneInterface.php on line 23

**Comment by ronaldtebrake** [comment]
Hi @kreativmind ,

This is due to the fact the dependencies for external libraries needed for the address module aren't installed (correctly). Did you try downloading the dependencies with composer before starting the installation through the UI? And were there any errors when running:

`php profiles/social/modules/contrib/composer_manager/scripts/init.php
composer drupal-rebuild
composer update -n --lock --verbose`

In our newest alpha release, which will be released soon, we will have a better check in the requirements during the installation to make sure you get feedback if all the dependencies are installed and available. And we will have full installation support through composer, which will make sure all the dependencies are handled correctly if you install the profile with composer. 

If we can assist you with anything else please let us now!

**Comment by kreativmind** [comment]
Ive ran those commands successfully and now I am going to www.mydomain.com/core/install.php to hopefully install it successfully. I have also downloaded addressing and dropped it into the modules folder.

**Comment by AurSol** [comment]
Hi.
@kreativmind, did you have success?

**Comment by kreativmind** [comment]
No. Had the same error messages again.

**Comment by kreativmind** [comment]
Still cannot get it to work. Not going to worry about trying to install it anymore. Thanks for trying to help.
