### ISSUE TITLE
behat not found in dev install

### ISSUE THREAD

**Issue by marqpdx** [goalgorilla/drupal_social#291]
Hi,

i have installed open social using the instructions here (https://github.com/goalgorilla/drupal_social/wiki/Installing-and-updating with the one amendment noted in the other issue). It runs fine.

When i goto run the Behat unit tests, following these instructions (https://github.com/goalgorilla/drupal_social/wiki/How-to-run-the-Behat-tests-locally), and i get an error:
`bash: behat: command not found`

has the docker install perhaps changed since the instructions were written?

thanks,
m

**Comment by ronaldtebrake** [comment]
Hi,

I think the instruction are still correct. But most likely we have committed a wrong composer.lock file, which doesn't include Behat. 
This will be fixed in the next beta release, but for now what you could do is try the following:

`docker exec -it social_behat bash`
`cd /root/.composer/`
`rm composer.lock`
`composer update` 

Thanks,
