### ISSUE TITLE
image styles not generated correctly when installing demo content

### ISSUE THREAD

**Issue by horvan** [goalgorilla/drupal_social#313]
I tried to install demo content with drush today and don't get images displayed  when the cpmmand is done. If I click on an image file in a picer of content the image is shown so it seems  image stiels donÄt apply correctly.

**Comment by miesz-ko** [comment]
Hello! Sorry it took so long to get back to you. We actually use the Drupal.org issue list for all issues and bugs; https://www.drupal.org/project/issues/social?categories=All

Maybe you can check if your issue is resolved in the newest release, and if not, post your issue in our Drupal.org issue list. Thanks! :)

Best, Mieszko
