### ISSUE TITLE
Committing the .lock file.

### ISSUE THREAD

**Issue by sylus** [goalgorilla/drupal_social#314]
Hi there!

I had a small question I was curious about and it was to do with Open Social not committing the composer.lock file.

I noticed for the platform.sh example you are committing the `composer.lock` but not for the docker build + default build. I was just curious if this was done intentionally?

Thank you so much ^_^!

**Comment by jaapjan** [comment]
Hey @sylus 

For the Platform.sh build we feel it is very important that the version is stable and tested by us. When we commit the composer.lock file we will know for sure that the working versions of the dependencies are used. Because of that we should probably consider adding it to [social_template](https://github.com/goalgorilla/social_template) as well but so far it did not gave us much issues.

The docker build is focussed on developers working on the project on local machines and not committing the lock file ensures that on each install the latest version is used.

In the open_social repository it does not add much value since it is a library, see also: https://getcomposer.org/doc/02-libraries.md#lock-file

Hope this answers your questions and if you have any feedback, feel free to re-open!
