### ISSUE TITLE
Gulp errors in gulp-sass

### ISSUE THREAD

**Issue by spoetnik** [goalgorilla/drupal_social#97]
Running Gulp results in two errors:

    [14:10:35] gulp-notify: [Gulp error in gulp-sass] css/src/materialize/_forms.scss
    Error: ".autocomplete-content li" failed to @extend "%clearfix".
           The selector "%clearfix" was not found.
           Use "@extend %clearfix !optional" if the extend should be able to fail.
            on line 255 of css/src/materialize/_forms.scss
    >>       @extend %clearfix;
       ------^

    [14:10:35] Finished 'script-materialize' after 740 ms
    [14:10:35] gulp-notify: [Gulp error in gulp-sass] css/src/styleguide/_sidenav.scss
    Error: ".side-nav" failed to @extend ".z-depth-1".
           The selector ".z-depth-1" was not found.
           Use "@extend .z-depth-1 !optional" if the extend should be able to fail.
            on line 134 of css/src/styleguide/_sidenav.scss
    >>   @extend .z-depth-1;
       --^

**Comment by peterpolman** [comment]
Yes! Nice find! I stumbled upon these when I cloned a fresh repo at the beginning of this week. Guess we cleaned up a bit to rigorously last week after we switched to bootstrap-sass and removed a lot of custom scss.

For now I already fixed them and they are ready to be merged in master. The first @extend should be @extend .clearfix and the @extend .z-depth-1 can be commented out since this scss is only used in the styleguide navigation (and doesn't realy break anything).

If you want to further discuss theming related stuff or run into trouble (You're probably not gonna have all the content images in the HIFI prototype;)) please add me on Skype: peter.polman. 

Ciao!

**Comment by spoetnik** [comment]
Thanks!
I am no hard-core developer, but am glad to help in any way with this promising distribution!
